---------------------------DROP TABLE-------------------------
DROP TABLE EMPLOYEE_INFO CASCADE CONSTRAINTS; 
DROP TABLE ADDITIONAL_SERVICES_AVAILED CASCADE CONSTRAINTS;
DROP TABLE INVOICE CASCADE CONSTRAINTS;
DROP TABLE CANCELLATION CASCADE CONSTRAINTS;
DROP TABLE FEEDBACK CASCADE CONSTRAINTS;
DROP TABLE RESERVATION CASCADE CONSTRAINTS;
DROP TABLE CUSTOMER_INFO CASCADE CONSTRAINTS;
DROP TABLE PACKAGE_DEALS CASCADE CONSTRAINTS;
DROP TABLE ROOM_SERVICE CASCADE CONSTRAINTS;
DROP TABLE ROOM CASCADE CONSTRAINTS;
DROP TABLE ROOM_TYPE CASCADE CONSTRAINTS; 
DROP TABLE HOTEL CASCADE CONSTRAINTS;

--------------------------DROP USERS----------------------------------
DROP USER hotel_manager;
DROP USER receiptionist;
DROP USER hotel_staff;
DROP USER customer;

-------------------------DROP VIEWS-----------------------------------
DROP VIEW Customer_View1;
DROP VIEW Customer_View2;
DROP VIEW Customer_View3;
DROP VIEW ADMIN_VIEW;
DROP VIEW HOTEL_STAFF_VIEW;
DROP VIEW ACCOUNTS_EXPENDIURE_MONTHLY_VIEW;
DROP VIEW ACCOUNTS_INCOME_MONTHLY_VIEW;
DROP VIEW Manager_View1;
DROP VIEW Manager_View2;
DROP VIEW Receptionist_View;
DROP VIEW ROOMS_BOOKED_MONTHLY_VIEW;
DROP VIEW NUMBER_OF_EMPLOYEES_VIEW;
DROP VIEW PACKAGES_AVAILED_AT_HOTEL;
DROP VIEW INCOME_FROM_PACKAGES_AVAILED_AT_HOTEL;

-------------------------DROP PACKAGES---------------------------------

DROP PACKAGE INSERT_TABLES;
-----------------------DROP PROCEDURES----------------------------------

DROP PROCEDURE BOOKING;
DROP PROCEDURE CHOOSE_HOTEL;
DROP PROCEDURE GENERATE_INVOICE;
DROP PROCEDURE ROOM_SERVICES;
DROP PROCEDURE SIGNUP;